### ISSUE TITLE
Optimization proposals!

### ISSUE THREAD

**Issue by jaimii** [PanischerPublishing/LevellingTools#2]
Hello! I have some suggestions to make this plugin slightly more optimized. 

- Proposal to stop experience gains once the tool reaches max level.

- Proposal to stop individual exp checks for grouped mobs in farms such as Enderman farms to improve tps performance.

- Proposal to edit the gained stats for levelling up the tools. (For example: Damage Dealt Multiplier: 0.1 Dig Speed Multiplier: 0.1)

Just a few small things that might help this plugin out, alright, thank you.

**Comment by PanischerPublishing** [comment]
Hey!

Thanks for your feedback and the suggestions, but I didn’t understand what
you‘ve meant in the second point. The update for the first point is already
done, I will release it when I added everything wanted.

Bye,
Panischer

jaimii ***@***.***> schrieb am Do. 20. Mai 2021 um 05:57:

**Comment by jaimii** [comment]
Hello Panischer!

In our minecraft server, we use a mob farm in the end called Enderman
farms, it's used to grind for enchantment xp. I noticed that there is a
huge lag spike when hitting the endermen in this said farm, dropping the
TPS from 20 to 16. I suspect that it's caused by the exp gains from using
the sword with the levellingtools plugin. Basically, I think that it's
doing individual checks for each enderman when hitting them, which lags the
server out because they're clumped together in one space, ticking each one
every sweep of the sword.

I propose a solution to reprogram a single tick for a group of mobs when
using the sweeping edge feature of a sword. Possibly fixing the tps drops.

I'm sorry for the very late reply, I'm very busy as of the moment, but
thank you for reaching out to me.

-Jaimii

**Comment by jaimii** [comment]
I also found this small exception bug that seems to glitch out the bukkit
EntityByDamageEntity event.

This is all I can gather from the logs, since it spammed the console:
https://mclo.gs/VYZn06Z

Also, here's the timings report of the server, if you need it for
reference: https://timings.aikar.co/?id=57ec9e248b02486395843b402aeed826

Thank you.

-Jaimii

**Comment by PanischerPublishing** [comment]
Oh okay! I will try to avoid level gain when it is caused by sweeping
damage, that should fix the problem.

jaimii ***@***.***> schrieb am Sa. 22. Mai 2021 um 05:31:

> Hello Panischer!
>
> In our minecraft server, we use a mob farm in the end called Enderman
> farms, it's used to grind for enchantment xp. I noticed that there is a
> huge lag spike when hitting the endermen in this said farm, dropping the
> TPS from 20 to 16. I suspect that it's caused by the exp gains from using
> the sword with the levellingtools plugin. Basically, I think that it's
> doing individual checks for each enderman when hitting them, which lags the
> server out because they're clumped together in one space, ticking each one
> every sweep of the sword.
>
> I propose a solution to reprogram a single tick for a group of mobs when
> using the sweeping edge feature of a sword. Possibly fixing the tps drops.
>
> I'm sorry for the very late reply, I'm very busy as of the moment, but
> thank you for reaching out to me.
>
> -Jaimii
>
